[profile.default]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1
bytecode_hash = "none" # The metadata hash removed from the bytecode (not the metadata itself).
# uncomment this to inspect storage layouts in build artifacts
# extra_output = ["storageLayout"]

src = "src"
out = "out"
libs = ["lib", "node_modules"]
cache_path  = "cache"

gas_limit = "18446744073709551615"
block_gas_limit = 300_000_000
memory_limit = 330554432
fuzz = { runs = 256 }

gas_reports = [
    "CSAccounting",
    "CSBondCore",
    "CSBondCurve",
    "CSBondLock",
    "CSEarlyAdoption",
    "CSFeeDistributor",
    "CSFeeOracle",
    "CSModule",
    "CSVerifier",
    "AssetRecovererLib",
]

fs_permissions = [
    { access = "read-write", path = "./out" },
    { access = "read-write", path = "./artifacts" },
    { access = "read", path = "./test/fixtures" },
]

[profile.ci]
verbosity = 3
fuzz = { runs = 10_000 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
